package com.smartstay.smartstay.responses.beds;

public record BedDetails(String bedName,
                         int bedId,
                         String hostelId,
                         boolean isBooked,
                         boolean isOnNotice,
                         boolean isOccupied,
                         Double rentAmount,
                         int roomId,
                         String freeFrom,
                         Double currentRent,
                         String currentTenantLeavingOn,
                         String bookingId,
                         String newTenantJoiningDate,
                         String currentTenantJoiningDate,
                         String currentTenantFirstName,
                         String currentTenantLastName,
                         String currentTenantProfilePic,
                         String currentTenantFullName,
                         String currentTenantInitials,
                         String currentTenantMobile,
                         Integer floorId,
                         String floorName,
                         String roomName,
                         String countryCode,
                         String currentTenantCustomerId,
                         String newTenantFirstName,
                         String newTenantLastName,
                         String newTenantFullName,
                         String newTenantProfilePic,
                         String newTenantInitials,
                         String newTenantMobile,
                         String newTenantCustomerId) {
}
